config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  # Users controller
  controller :users do
    get 'signup' => :signup
    post 'create_user' => :create_user
    get 'login' => :login
    post 'log_user' => :log_user
    get 'logout' => :logout
    get 'profile/:id' => :profile, as: 'profile'
    get 'deactivate/:id' => :deactivate, as: 'deactivate'
    delete 'delete_account/:id' => :delete_account, as: 'delete_account'
  end

  # Pages
  controller :pages do
    get 'index' => :index
    get 'welcome' => :welcome
    get 'explore' => :explore
  end

  # Posts
  controller :posts do
    get 'new_post' => :new_post
    post 'create_post' => :create_post
    get 'view_post/:id' => :view_post, as: 'view_post'
    delete 'delete_post/:id' => :delete_post, as: 'delete_post'
    get 'edit_post/:id' => :edit_post, as: 'edit_post'
    patch 'update_post/:id' => :update_post, as: 'update_post'
  end

  # Follow
  controller :follow do
    post 'follow/:id' => :follow, as: 'follow'
    post 'unfollow/:id' => :unfollow, as: 'unfollow'
    get 'followers/:id' => :followers, as: 'followers'
    get 'followings/:id' => :followings, as: 'followings'
  end

  # Like system
  controller :like do
    post 'like/:id' => :like, as: 'like'
    post 'unlike/:id' => :unlike, as: 'unlike'
    get 'likes/:id' => :likes, as: 'likes'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
end

app/models/like.rb
class Like < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 5, :maximum => 250 }
  validates :content, :length => { :minimum => 5 }

end

app/models/user.rb
class User < ApplicationRecord

  validates :username, :email, :password, :presence => true
  validates :username, :length => { :minimum => 4 }
  validates :username, :email, :uniqueness => { :message => "already taken!!" }

end

app/models/view.rb
class View < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def loggedIn(path=login_path)
    redirect_to path if !session[:id]
  end

  def loggedOut
    redirect_to root_path if session[:id]
  end

  def is_user_valid(id)
    user = User.find_by(:id => id)
    return user == nil ? false : true
  end

  def invalid_user
    redirect_to root_path, :notice => "User not found!!"
  end

end

app/controllers/follow_controller.rb
class FollowController < ApplicationController

  include ApplicationHelper

  def follow
    Follow.create(:follow_by => session[:id], :follow_to => params[:id])
    redirect_to profile_path(params[:id]), :notice => "Followed #{get(params[:id], 'username')}!!"
  end

  def unfollow
    @f = Follow.where(:follow_by => session[:id], :follow_to => params[:id])
    @f.destroy_all
    redirect_to profile_path(params[:id]), :notice => "Unfollowed #{get(params[:id], 'username')}!!"
  end

  def followers
    loggedIn
    if is_user_valid(params[:id])
      @followers = Follow.where(:follow_to => params[:id]).order(id: :desc)
    else
      invalid_user
    end
  end

  def followings
    loggedIn
    if is_user_valid(params[:id])
      @followings = Follow.where(:follow_by => params[:id]).order(id: :desc)
    else
      invalid_user
    end
  end

end

app/controllers/like_controller.rb
class LikeController < ApplicationController

  def like
    Like.create(:like_by => session[:id], :post => params[:id])
    redirect_to view_post_path(params[:id]), :notice => "Post Liked!!"
  end

  def unlike
    @ul = Like.where(:like_by => session[:id], :post => params[:id])
    @ul.destroy_all
    redirect_to view_post_path(params[:id]), :notice => "Post Unliked!!"
  end

  def likes
    loggedIn
    @likes = Like.where(:post => params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    loggedIn welcome_path
    @id = session[:id]
    @username = session[:username]
  end

  def welcome
    loggedOut
  end

  def explore
    loggedIn
    @explore = User.where.not(:id => session[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new_post
    loggedIn
    @post = Post.new
  end

  def create_post
    @post = Post.new(post_params)
    if @post.save
      @p = Post.find_by(:id => @post.id)
      @p.update_attributes(:user => session[:id])
      redirect_to view_post_path(@post.id), :notice => "Post Created!!"
    else
      render 'new_post'
    end
  end

  def view_post
    loggedIn
    @post = Post.find_by(:id => params[:id])
    @likes = Like.where(:post => params[:id]).count
  end

  def delete_post
    Like.find_by(:post => params[:id]).destroy
    @post = Post.find_by(:id => params[:id])
    @post.destroy
    redirect_to profile_path(session[:id]), :notice => "Post deleted!!"
  end

  def edit_post
    loggedIn
    @post = Post.find_by(:id => params[:id])
  end

  def update_post
    @post = Post.find_by(:id => params[:id])
    if @post.update_attributes(post_params)
      redirect_to view_post_path(params[:id]), :notice => "Post edited!!"
    else
      render 'edit_post'
    end
  end

  private def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # User Signup
  def signup
    loggedOut
    @user = User.new
  end

  def create_user
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id
      session[:username] = @user.username
      redirect_to profile_path(@user.id), :notice => "Hello, #{@user.username}!!"
    else
      render "signup"
      flash[:notice] = "Unable to signup!!"
    end
  end

  # User login
  def login
    loggedOut
  end

  def log_user
    user = User.find_by(username: params[:username])
    if user and user.password == params[:password]
      session[:id] = user.id
      session[:username] = user.username
      redirect_to root_path, :notice => "Hello, #{user.username}!!"
    else
      flash[:notice] = "Invalid username or password!!"
      render 'login'
    end
  end

  def logout
    reset_session
    redirect_to login_path, :notice => "You are now logged out!!"
  end

  def profile
    loggedIn
    if is_user_valid(params[:id])

      @user = User.find_by(:id => params[:id])

      if session[:id] != @user.id
        View.create(:view_by => session[:id], :view_to => params[:id])
      end

      @posts = Post.where(:user => @user.id).order(id: :desc)
      @followers = Follow.where(:follow_to => @user.id).count
      @followings = Follow.where(:follow_by => @user.id).count
      @views = View.where(:view_to => @user.id).count

      render 'profile'
    else
      invalid_user
    end
  end

  def deactivate
    loggedIn
    if is_user_valid(params[:id])
      render 'deactivate'
    else
      invalid_user
    end
  end

  def delete_account
    user = session[:id]

    View.where(:view_by => user).destroy_all
    View.where(:view_to => user).destroy_all
    Follow.where(:follow_by => user).destroy_all
    Follow.where(:follow_to => user).destroy_all
    Like.where(:like_by => user).destroy_all

    Post.where(:user => user).each do |post|
      pl = Like.find_by(:post => post.id)
      pl.destroy unless pl == nil
    end

    Post.where(:user => user).destroy_all
    User.find_by(:id => user).destroy

    reset_session
    redirect_to login_path, :notice => "Your account is now deactivated!!"
  end

  private def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def get(id, what)
    @find = User.find_by(:id => id)
    return @find[what]
  end

  def is_following(id)
    f = Follow.where(:follow_by => session[:id], :follow_to => id)
    return f.count == 0 ? false : true
  end

  def no_of_followers(user)
    f = Follow.where(:follow_to => user)
    return f.count
  end

  def username_decider(id)
    @username = get(id, "username")
    if @username == session[:username]
      return "You"
    else
      return @username
    end
  end

  def liked(post)
    like = Like.where(:like_by => session[:id], :post => post)
    return like.count == 0 ? false : true
  end

end

app/helpers/follow_helper.rb
module FollowHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/follow/followers.html.erb
<%= content_for :title, "#{get(params[:id], 'username')}'s Followers" %>

<div class="explore">

  <div class="explores">

    <% if !@followers.empty? %>
      <% @followers.each do |f| %>
        <%= render 'partials/list', type: 'followers', f: f %>
      <% end %>
    <% end %>

    <% if @followers.empty? %>
      <%= render 'partials/nothing', mssg: "#{get(params[:id], 'username')} has no followers!!" %>
    <% end %>

    <% if !@followers.empty? %>
      <%= render 'partials/end' %>
    <% end %>

  </div>

</div>

app/views/follow/followings.html.erb
<%= content_for :title, "#{get(params[:id], 'username')}'s Followings" %>

<div class="explore">

  <div class="explores">

    <% if !@followings.empty? %>
      <% @followings.each do |f| %>
        <%= render 'partials/list', type: 'followings', f: f %>
      <% end %>
    <% end %>

    <% if @followings.empty? %>
      <%= render 'partials/nothing', mssg: "#{get(params[:id], 'username')} has no followers!!" %>
    <% end %>

    <% if !@followings.empty? %>
      <%= render 'partials/end' %>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<%= render 'partials/header' %>

<div class="notes_wrapper">
  <%= yield %>
</div>

<%= render 'partials/footer' %>

app/views/like/likes.html.erb
<%= content_for :title, "Likes" %>

<div class="explore">

  <div class="explores">

    <% if !@likes.empty? %>
      <% @likes.each do |l| %>
        <%= render 'partials/list', type: 'likes', f: l %>
      <% end %>
    <% end %>

    <% if @likes.empty? %>
      <%= render 'partials/nothing', mssg: "Post has no likes!!" %>
    <% end %>

    <% if !@likes.empty? %>
      <%= render 'partials/end' %>
    <% end %>

  </div>

</div>

app/views/pages/explore.html.erb
<%= content_for :title, "Explore" %>

<div class="explore">

  <div class="explores">

    <% if !@explore.empty? %>
      <% @explore.each do |e| %>
        <%= render 'partials/list', type: 'explores', f: e %>
      <% end %>
    <% end %>

    <% if @explore.empty? %>
      <%= render 'partials/nothing', mssg: "No one to explore!!" %>
    <% end %>

    <% if !@explore.empty? %>
      <%= render 'partials/end' %>
    <% end %>

  </div>

</div>

app/views/pages/index.html.erb
<% content_for :title, "Home" %>

<div class="welcome_div">
  <%= image_tag "dutch.gif" %>
</div>

app/views/pages/welcome.html.erb
<% content_for :title, "Welcome" %>

<div class="welcome_div">
  <%= image_tag "omg.png" %>
</div>

app/views/partials/_end.html.erb
<div class="page_end">
  <span>Looks like you've reached the end</span>
</div>

app/views/partials/_footer.html.erb
<script src="http://localhost:3000/js/dist/bundle.js"></script>
</body>
</html>

app/views/partials/_header.html.erb
<%= render 'partials/tophead' %>

<% if flash.any? %>
  <%= render 'partials/mssg', mssg: flash[:notice] %>
<% end %>

<% if !session[:id] %>
  <div class="index_header">
    <div class="right">
      <%= link_to "Home", welcome_path %>
      <%= link_to "Signup", signup_path %>
      <%= link_to "Login", login_path %>
    </div>
  </div>
<% else %>
  <div class="header_loggedin">
    <div class="left">
      <%= link_to "Home", root_path %>
      <%= link_to "New post", new_post_path %>
      <%= link_to "Explore", explore_path %>
      <%= link_to  "Deactivate", deactivate_path(session[:id]) %>
    </div>
    <div class="right">
      <%= link_to "Profile", profile_path(session[:id]) %>
      <%= link_to "Logout", logout_path %>
    </div>
  </div>
<% end %>

app/views/partials/_list.html.erb
<%
  if type == "followers"
    user = f.follow_by
  elsif type == "followings"
    user = f.follow_to
  elsif type == "explores"
    user = f.id
  elsif type == "likes"
    user = f.like_by
  end
%>

<div class="explores_list">
  <div class="exl_main">
    <%= image_tag "ruby-red.png" %>
      <div class="exl_content">
        <span class="exl_username"><%= username_decider(user) %></span>
        <div class="exl_desc">
          <span class="exl_email"><%= get(user, "email") %></span>
          <span class="exl_desc_sep">•</span>
          <span class="exl_followers"><%= no_of_followers(user) %> Followers</span>
        </div>
      </div>
  </div>
  <div class="exl_ff">
    <%= link_to "Profile", profile_path(user), :class => "pri_btn" %>
  </div>
</div>

app/views/partials/_mssg.html.erb
<div class="flash">
  <span class="flash_mssg"><%= mssg %></span>
  <span class="flash_icon">
    <i class="material-icons">clear</i>
  </span>
</div>

app/views/partials/_nothing.html.erb
<div class='home_last_mssg'>
  <%= image_tag "large.jpg" %>
    <span><%= mssg %></span>
</div>

app/views/partials/_post.html.erb
<div class="note">
  <div class="note_header common_header">
    <%= image_tag "ruby-red.png" %>
    <div class="note_h_left">
      <span class="note_username"><%= get(post.user, "username") %></span>
      <span class='note_time'><%= post.created_at %></span>
    </div>
  </div>
  <div class="note_title">
    <span><%= post.title %></span>
  </div>
  <div class="note_content">
    <span><%= post.content %></span>
  </div>
  <div class="note_actions">
    <%= link_to "View", view_post_path(post.id), class: "sec_btn" %>
  </div>
</div>

app/views/partials/_tophead.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> • Mini Social Network</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

app/views/posts/edit_post.html.erb
<%= content_for :title, "Edit Post" %>

<div class="edit">

  <div class="edit_info">
    <%= image_tag  "ruby-red.png", class: "edit_img", alt: "Your avatar" %>
    <span>Edit Post</span>
  </div>

  <%= form_for @post, url: { action: 'update_post' } do |f| %>

    <% if @post.errors.any? %>
      <%= render 'partials/mssg', mssg: @post.errors.full_messages[0] %>
    <% end %>

    <div class="eu_div">
      <span class='edit_span'>Title</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Title..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_div">
      <span class='edit_span'>Content</span>
      <%= f.text_area :content, placeholder: "Content..", autofocus: true, class: "e_bio", spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_btns">
      <%= f.submit "Update Post" %>
    </div>

  <% end %>

</div>

app/views/posts/new_post.html.erb
<%= content_for :title, "New Post" %>

<div class="edit">

  <div class="edit_info">
    <%= image_tag  "ruby-red.png", class: "edit_img", alt: "Your avatar" %>
      <span>Create Post</span>
  </div>

  <%= form_for @post, url: { action: 'create_post' } do |f| %>

    <% if @post.errors.any? %>
      <%= render 'partials/mssg', mssg: @post.errors.full_messages[0] %>
    <% end %>

    <div class="eu_div">
      <span class='edit_span'>Title</span>
      <%= f.text_field :title, class: "e_username", placeholder: 'Title..', autofocus: true, spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_div">
      <span class='edit_span'>Content</span>
      <%= f.text_area :content, placeholder: "Content..", autofocus: true, class: "e_bio", spellcheck:false, autocomplete: false %>
    </div>
    <div class="eb_btns">
      <%= f.submit "Create Post" %>
    </div>

  <% end %>

</div>

app/views/posts/view_post.html.erb
<%= content_for :title, "View Post" %>

<div class="home">
  <div class="blog">
    <div class="blog_c">
      <span class="blog_title"><%= @post.title %></span>
      <span class="blog_content"><%= @post.content %></span>
    </div>
    <div class="blog_actions">
      <div class="b_a_left">
        <%=
          if liked(@post.id)
            link_to "Unlike", unlike_path(@post.id), :class => "pri_btn", :method => :post
          else
            link_to "Like", like_path(@post.id), :class => "pri_btn", :method => :post
          end
        %>
        <%= link_to "#{@likes} Likes", likes_path(@post.id), :class => "sec_btn" %>
      </div>
      <div class="b_a_right">
        <%= link_to "Edit Post", edit_post_path(@post.id), class: "sec_btn" %>
        <%=
          link_to "Delete",
          delete_post_path(@post.id),
          :class => "sec_btn blog_dlt",
          :data => { :confirm => "Are you sure?" },
          :method => :delete
        %>
        <%= link_to "Done", profile_path(session[:id]), class: "pri_btn blog_back" %>
      </div>
    </div>
  </div>
</div>

app/views/users/deactivate.html.erb
<%= content_for :title, "Deactivate your account" %>

<div class="registered deactivate">
  <span class="deactivate_title">Deactivate your account?</span>
  <span>All of your posts, followers, likes & other info will be permanently deleted. And you won't be able to find it again.</span>
  <div class="deactivate_btn">
    <%=
      link_to "Deactivate",
      delete_account_path(session[:id]),
      :class => "pri_btn d_btn",
      :data => { :confirm => "Are you sure?" },
      :method => :delete
    %>
  </div>
</div>

app/views/users/login.html.erb
<% content_for :title, "Login" %>

<div class="log_sign">
  <%= link_to "Need an account?", signup_path, class: "pri_btn" %>
</div>

<div class="login cua ">

  <div class="display_text">
    <span>Get started again</span>
  </div>

  <%= form_tag log_user_path do %>
    <%= text_field_tag :username, params[:username], class:"l_username", autofocus:true, required:true, spellcheck:false, autocomplete:false, placeholder:'Username' %>
    <%= password_field_tag :password, params[:password], class:"l_password", required:true, placeholder:'Password' %>
    <%= submit_tag "Login to continue", class:"l_submit" %>
  <% end %>

</div>

app/views/users/profile.html.erb
<%
  @id = @user.id
  @username = @user.username
  @email = @user.email
%>

<% content_for :title, "@#{@username}" %>

<div class="profile_data"
  data-get_id="<%= @id %>"
  data-get_username="<%= @username %>"
  data_get_email="<%= @email %>"
></div>

<div class="aligner">

  <div class='user_banner'>
    <div class="profile_img_div">
      <%= image_tag "ruby-red.png" %>
    </div>
    <div class="user_buttons">
      <% if session[:id] == @id %>
        <%= link_to "Create Post", new_post_path, class: "create_note_btn pri_btn" %>
      <% else %>
        <% if is_following(@id) %>
          <%= link_to "Unfollow", unfollow_path(@id), :method => :post, :class => "unfollow pri_btn" %>
          <% else %>
          <%= link_to "Follow", follow_path(@id), :method => :post, :class => "follow pri_btn" %>
        <% end %>
      <% end %>
    </div>
    <div class="user_info">
      <%= link_to @username, profile_path(@id), class: "user_main_link" %>
      <span class="user_no_notes"><%= @email %></span>
      <hr />
      <div class="user_stats">
        <div class="stat_post">
          <span class="stat_hg"><%= @posts.length %></span>
          <span class="stat_nhg">Posts</span>
        </div>
        <div class="stat_followers">
          <span class="stat_hg"><%= @followers %></span>
          <%= link_to "Followers", followers_path(@id), :class => "stat_nhg" %>
        </div>
        <div class="stat_followings">
          <span class="stat_hg"><%= @followings %></span>
          <%= link_to "Followings", followings_path(@id), :class => "stat_nhg" %>
        </div>
        <div class="stat_views">
          <span class="stat_hg"><%= @views %></span>
          <span class="stat_nhg">Profile views</span>
        </div>
      </div>
    </div>
  </div>

  <div class="notes">

    <% unless @posts.empty? %>
      <% @posts.each do |post| %>
        <%= render 'partials/post', post: post %>
      <% end %>
    <% end %>

    <% if @posts.empty? %>
      <%
        session[:id] == @id ?
          @mssg = "No posts for you. Go ahead and create one!!"
        :
          @mssg = "#{@username} has no posts!!"
      %>
      <%= render 'partials/nothing', mssg: @mssg %>
    <% end %>

    <% unless @posts.empty? %>
      <%= render 'partials/end' %>
    <% end %>

  </div>

</div>

app/views/users/signup.html.erb
<% content_for :title, "Signup" %>

<div class="log_sign">
  <%= link_to "Already have an account?", login_path, class: "pri_btn" %>
</div>

<div class="register cua ">

  <div class="display_text">
    <span>Get started now and let the fun begins</span>
  </div>

  <%= form_for @user, url: { action: 'create_user' } do |f| %>

    <% if @user.errors.any? %>
      <%= render 'partials/mssg', mssg: @user.errors.full_messages[0] %>
    <% end %>

    <%= f.text_field :username, class:"r_username", autofocus:true, spellcheck:false, autocomplete:false, placeholder:'Username', required: true %>
    <%= f.email_field :email, class:"r_email", spellcheck:false, autocomplete:false, placeholder:'Email', required:true %>
    <%= f.password_field :password, class: "r_password", placeholder: 'Password', required: true %>
    <%= f.submit "Signup for free", class:"r_submit" %>

  <% end %>

</div>